version: '3'
services:
  nginx:
    build: 
      context: .
      args:
        - server_name=$nginx_server_name
        - host_port=$nginx_host_port
        - cert_file=$nginx_cert_file
    ports:
      - '$nginx_host_port:443'
  keycloak:
    image: 'jboss/keycloak'
    environment:
      - KEYCLOAK_PASSWORD=pass
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
